# Generated by Django 5.2.17 on 2026-09-14 22:52

import apps.catalog.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_published", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, default="", max_length=255)),
                ("category", models.CharField(blank=True, default="", max_length=160)),
                (
                    "legacy_collection_label",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "scent_family",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "concentration",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("currency", models.CharField(default="BDT", max_length=3)),
                ("short_description", models.TextField(blank=True, default="")),
                ("full_description", models.TextField(blank=True, default="")),
                (
                    "top_notes",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "heart_notes",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "base_notes",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                ("longevity", models.CharField(blank=True, default="", max_length=80)),
                ("sillage", models.CharField(blank=True, default="", max_length=80)),
                (
                    "seasons",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "occasions",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                (
                    "style_tags",
                    models.JSONField(
                        default=list,
                        validators=[apps.catalog.validators.validate_string_list],
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_bestseller", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "sort_order"],
                        name="catalog_prod_pub_order_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_published", "sort_order"],
                        name="catalog_prod_feat_idx",
                    ),
                    models.Index(
                        fields=["is_bestseller", "is_published", "sort_order"],
                        name="catalog_prod_best_idx",
                    ),
                    models.Index(
                        fields=["is_new", "is_published", "sort_order"],
                        name="catalog_prod_new_idx",
                    ),
                    models.Index(
                        fields=["scent_family", "is_published", "sort_order"],
                        name="catalog_prod_family_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["collection_id", "sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                related_name="collections",
                through="catalog.CollectionProduct",
                to="catalog.product",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=32)),
                (
                    "ml",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("in_stock", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product_id", "sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionproduct",
            index=models.Index(
                fields=["collection", "sort_order"], name="catalog_coll_prod_order_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionproduct",
            constraint=models.UniqueConstraint(
                fields=("collection", "product"), name="catalog_collection_product_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["is_published", "sort_order"], name="catalog_coll_pub_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(
                fields=["product", "is_active", "sort_order"],
                name="catalog_variant_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("ml__gt", 0)), name="catalog_variant_ml_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="catalog_variant_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("compare_at_price__isnull", True),
                    ("compare_at_price__gte", models.F("price")),
                    _connector="OR",
                ),
                name="catalog_variant_compare_gte_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "label"), name="catalog_variant_product_label_uniq"
            ),
        ),
    ]
