# Generated by Django 5.2.17 on 2026-09-14 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "secure_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("asset_id", models.CharField(blank=True, default="", max_length=255)),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("format", models.CharField(blank=True, default="", max_length=16)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "cloudinary_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image",
                        to="catalog.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["collection_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "cloudinary_public_id",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                (
                    "secure_url",
                    models.URLField(blank=True, default="", max_length=2048),
                ),
                ("asset_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("gallery", "Gallery")],
                        default="gallery",
                        max_length=16,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, default="", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("format", models.CharField(blank=True, default="", max_length=16)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("byte_size", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "cloudinary_version",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product_id", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["product", "role", "sort_order"],
                        name="cat_prod_img_role_idx",
                    ),
                    models.Index(
                        fields=["product", "sort_order"],
                        name="catalog_prod_img_order_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("role", "primary")),
                        fields=("product",),
                        name="catalog_product_one_primary_image",
                    )
                ],
            },
        ),
    ]
